config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'welcome/index'
  get 'reset'  => 'welcome#reset', as: :reset
  get 'job'    => 'welcome#job',   as: :job

  get 'search' => 'search#index', as: :search_index

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  # Maximum time in which a Search can be updated or it will be considered
  # expired.
  #
  # After this time we are assuming the sentence is complete.
  TIME_TO_EXPIRE = 5.seconds

  # This helps us to control which Searches need be accounted for by the
  # background job.
  enum status: [:pending, :processing, :processed]

  # Empty search doesn't matter for us.
  # They also need the IP.
  validates :text, :ip, presence: true

  # Get all searches that will not be updated no more.
  scope :expired, -> { where('updated_at < ?', Time.current - TIME_TO_EXPIRE) }


  # Look for the last search for this IP within the expiration period
  # (TIME_TO_EXPIRE) and then update the text. 
  #
  # If nothing is found, it creates a new record.
  def self.save(ip, text)
    limit_time  = Time.current - TIME_TO_EXPIRE
    last_search = Search.where('ip = ? and updated_at > ?', ip, limit_time)
                        .order('updated_at ASC').last

    if last_search
      last_search.update(text: text)
      last_search
    else
      Search.create(text: text, ip: ip)
    end
  end

  # Clear all the Searches and SearchSummaries in database.
  def self.reset
    Search.delete_all
    SearchSummary.delete_all
  end
end

app/models/search_summary.rb
class SearchSummary < ApplicationRecord
  validates :text, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    Search.save(request.ip, params[:q])
    head :ok
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @summaries = SearchSummary.order(hits: :desc).limit(10)
  end

  def reset
    Search.reset
    redirect_to root_url
  end

  def job
    SearchSummaryJob.perform_later
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchAnalytics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/welcome/index.html.erb
<div class="header">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-6">
        <div class="logo">
          <%= link_to '/' do %>
            <%= image_tag 'logo.png' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-6">
        <div class="search-box">
          <%= text_field_tag :q, '', class: 'form-control', placeholder: 'Search...' %>
        </div>
      </div>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-6">
        <i class="fa fa-circle-o-notch"></i>
        <div class="loader d-none">Loading...</div>
      </div>
    </div>
  </div>
</div>

<div class="analytics">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-6">
        <div class="row">
          <div class="col-4">
            <h4>Analytics</h4>
          </div>
          <div class="col-8 text-md-right">
            <%= link_to 'Enqueue Job', job_url %> |
            <%= link_to 'Reload', '' %> |
            <%= link_to 'Clear stats', reset_url %>
          </div>
        </div>
        <% if @summaries.empty? %>
          <p>
          <em>No data. Try simulating a search and then enqueeing a job.</em>
          </p>
        <% end %>
        <ol>
          <% @summaries.each do |summary| %>
            <li><%= summary.text %> (<%= pluralize summary.hits, 'search' %>)</li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>

<div class="how-works">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-6">
        <h4>How it works</h4>
        <p>
          The goal here is to generate insight of content in the Knowlegde Base
          by using the user searches like inspiration. The as more the users
          are looking for the same content, as more it would be important.
        </p>

        <p>
          The challange is don't save partial query sentences once we 
          are using a <strong>realtime search box.</strong>
        </p>

        <p>
        <strong>The solution was use the time.</strong> So, those are the defined rules:
          <ol>
            <li>Search every <strong>750ms</strong> when the user stops to type;</li>
            <li>Create a record (Search Model) with the entered term;</li>
            <li>Update the last search record it was entered in the last <strong>5 seconds</strong>.</li>
          </ol>
        </p>

        <p>
          After save those records we need to account the amount of times the same search 
          was done. For this we defined a Job that look for all the searches updated for more than 
          <strong>5 seconds ago</strong>. I assumed their sentemces are complete.
        </p>

        <p>
          <u>Important:</u> 
            I have not care a lot about UX, so some things require
            the user interation and are not automatic:
          <ul>
            <li>
              Schedule jobs. The ideia is run the job every 1 hour, but I
              haven't configure this on Heroku. So you need to click on
              "Enqueuee Job".
            </li>
            <li>
              Update analytics. I am not using "Ajax" here to update the list
              of top 10 searches.  Because this I created the "Reload" link,
              that simply reloads the page.
            </li>
          </ul>
        </p>

        <h4>Stack</h4>

        <p>
          I tryied to use the minimum.
        </p>

        <ul>
          <li>Rails 5 (full stack)</li>
          <li>Minitest</li>
          <li>PostgreSQL</li>
          <li>Sidekiq</li>
        </ul>

        <h4>Finally</h4>

        <p>
          I hope I have achieved what you guys hoped.
        </p>

        <p>
          Thanks for the time.
        </p>

        <p>
          Lucas Castro
        </p>
      </div>
    </div>
  </div>
</div>